name: dev-branch-deployment
on:
  push:
    branches-ignore:
      - main
jobs:
  dev-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        name: Set up python
        with: 
          python-version: 3.11
      - name: Install python dependencies
        run: pip install -r requirements.txt
  
  dev-deploy:
    runs-on: ubuntu-latest
    steps:
